network separation and integrated
unitedstack/medusa pull request #11
Opened 2017-10-09 06:45 UTC by zkn111

Change-Id: I3010a82b9cc6238b0de55b4dc2094a4253877682

network separation and integrated
@PengJiyuan

2017-10-09 06:54 UTC, zkn111 commented
admin:
add network 、subnet 、router new function and paging and search 
all function on the basis of project ID

@PengJiyuan

2017-10-10 09:32 UTC, PengJiyuan commented on modules/network/lang.json
> +    "external_network": "External Network",
the key external_network is duplicate in 2 files:
halo/client/applications/admin/modules/network-agents/lang.json
halo/client/applications/admin/modules/network/lang.json

2017-10-10 09:42 UTC, PengJiyuan commented on locale/lang.json
> -    "compute_services": "计算服务",
...

2017-10-10 11:48 UTC, PengJiyuan commented on modules/network/pop/create_network/index.js
> +      phyNet.forEach(item => {
phyNet.forEach is not a function。
好好检查自己的代码，好好测试。

2017-10-11 01:57 UTC, zkn111 commented on modules/network/pop/create_network/index.js
> +      phyNet.forEach(item => {
这个是因为你的配置文件没有neutron_network_vlanranges这个字段吧

2017-10-13 07:17 UTC, PengJiyuan requested changes

2017-10-13 07:17 UTC, PengJiyuan commented on modules/subnet/pop/create_subnet/add_hostroutes.jsx
> +    this.state = {
// deep clone

2017-10-13 07:20 UTC, PengJiyuan approved these changes

2017-10-13 07:23 UTC, merged